// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using doanthi.Data;

#nullable disable

namespace doanthi.Migrations
{
    [DbContext(typeof(doanthiDBContext))]
    [Migration("20230215103323_addUserToDatabase")]
    partial class addUserToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("doanthi.Models.Hoadon", b =>
                {
                    b.Property<int>("Hoadon_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Hoadon_id"), 1L, 1);

                    b.Property<string>("NgaylapHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.Property<int>("User_id1")
                        .HasColumnType("int");

                    b.HasKey("Hoadon_id");

                    b.HasIndex("User_id1");

                    b.ToTable("Hoadons");
                });

            modelBuilder.Entity("doanthi.Models.Hoadon_Tinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Hoadon_id")
                        .HasColumnType("int");

                    b.Property<int>("Hoadon_id1")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sanpham_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Hoadon_id1");

                    b.HasIndex("Sanpham_id");

                    b.ToTable("hoadon_Tinhs");
                });

            modelBuilder.Entity("doanthi.Models.Khachhang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Khachhangs");
                });

            modelBuilder.Entity("doanthi.Models.Sanpham", b =>
                {
                    b.Property<int>("Sanpham_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sanpham_id"), 1L, 1);

                    b.Property<string>("HSD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameSP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NgayNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sanpham_id");

                    b.ToTable("Sanphams");
                });

            modelBuilder.Entity("doanthi.Models.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phanquyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("doanthi.Models.Hoadon", b =>
                {
                    b.HasOne("doanthi.Models.User", "User")
                        .WithMany("Hoadon")
                        .HasForeignKey("User_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("doanthi.Models.Hoadon_Tinh", b =>
                {
                    b.HasOne("doanthi.Models.Hoadon", "Hoadon")
                        .WithMany("Hoadon_Tinh")
                        .HasForeignKey("Hoadon_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("doanthi.Models.Sanpham", "Sanpham")
                        .WithMany("Hoadon_Tinh")
                        .HasForeignKey("Sanpham_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hoadon");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("doanthi.Models.Hoadon", b =>
                {
                    b.Navigation("Hoadon_Tinh");
                });

            modelBuilder.Entity("doanthi.Models.Sanpham", b =>
                {
                    b.Navigation("Hoadon_Tinh");
                });

            modelBuilder.Entity("doanthi.Models.User", b =>
                {
                    b.Navigation("Hoadon");
                });
#pragma warning restore 612, 618
        }
    }
}
